import IconTitle from 'components/common/ui/IconTitle';
import LoadingPage from 'components/common/ui/LoadingPage';
import Head from 'next/head';
import { BiGift } from 'react-icons/bi';
import AddProdutoForm from 'components/admin/Produtos/AddProduto';
import { ToastContainer, ToastContainerProps } from 'react-toastify';
import { useState } from 'react';
import Modal from 'components/common/ui/Modal';

const toastContainerSettings = {
    position: 'bottom-right',
    autoClose: 2000,
    hideProgressBar: false,
    newestOnTop: false,
    closeOnClick: true,
    rtl: false,
    pauseOnFocusLoss: true,
    draggable: true,
    pauseOnHover: true,
    theme: 'light',
} as ToastContainerProps;

const AddProduto = () => {
    const [modalVisible, setModalVisible] = useState(false);
    const [modalContent, setModalContent] = useState<JSX.Element>();

    return (
        <>
            <Head>
                <title>Adicionar Produto</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className="w-full flex-col items-center p-8">
                <IconTitle
                    icon={<BiGift />}
                    title={'Adicionar Produto'}
                    size={{ icon: 'text-3xl', title: 'text-2xl' }}
                    color={'text-violet-600'}
                />
                <AddProdutoForm
                    setModalContent={setModalContent}
                    setModalVisible={setModalVisible}
                />

                <ToastContainer {...toastContainerSettings} />
            </div>

            <Modal
                show={modalVisible}
                handleClose={() => setModalVisible(false)}
            >
                {modalContent}
            </Modal>
        </>
    );
};

AddProduto.auth = {
    role: 'admin',
    loading: <LoadingPage />,
    unauthorized: '/Login',
};

export default AddProduto;
