import Head from 'next/head';
import { motion } from 'framer-motion';

import LoadingPage from 'components/common/ui/LoadingPage';
import { CartProvider } from 'contexts/CartContext';
import List from 'components/carrinho/List';
import {
    ConfirmOrder,
    ConfirmOrderMobile,
} from 'components/carrinho/ConfirmOrder';

const Carrinho = () => {
    return (
        <>
            <Head>
                <title>Coelhão Store</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <motion.main
                exit={{ opacity: 0 }}
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                transition={{ duration: 0.3 }}
                className="flex min-h-screen w-full items-start justify-center bg-violet-100 sm:py-10"
            >
                <CartProvider>
                    <List />
                    <ConfirmOrder />
                    <ConfirmOrderMobile />
                </CartProvider>
            </motion.main>
        </>
    );
};

Carrinho.auth = {
    role: 'user',
    loading: <LoadingPage />,
    unauthorized: '/Login',
};

export default Carrinho;
