import type { NextPage } from 'next';
import { motion } from 'framer-motion';
import Head from 'next/head';

import ProdutosList from 'components/common/ui/ProdutosList';
import { gql, useQuery } from '@apollo/client';
import { ThreeDots } from 'react-loader-spinner';

const TODOS_PRODUTOS = gql`
    query {
        TODOS_PRODUTOS: allProdutos {
            prod_cod
            prod_nome
            prod_preco
            categoria {
                cat_nome
            }
            marca {
                marca_nome
            }
            produto_imagem {
                img_link
                img_ordem
                img_position
            }
        }
    }
`;

const Home: NextPage = () => {
    const { data, loading, error } = useQuery(TODOS_PRODUTOS);

    return (
        <>
            <Head>
                <title>Coelhão Store</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <motion.main
                exit={{ opacity: 0 }}
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                transition={{ duration: 0.3 }}
                className="flex min-h-screen w-screen flex-col items-center bg-violet-100"
            >
                <div className="w-full">
                    <img
                        style={{ minHeight: '200px' }}
                        className="w-full object-cover"
                        src="/images/home_banner.png"
                    />
                </div>

                {loading ? (
                    <ThreeDots
                        width="100"
                        height="100"
                        color="#7c3aed"
                        ariaLabel="Loading..."
                    />
                ) : error ? (
                    <span className="m-5 text-xl text-violet-900">
                        Houve um erro ao buscar podutos, tente novamente mais
                        tarde!
                    </span>
                ) : data?.TODOS_PRODUTOS.length > 0 ? (
                    <ProdutosList data={data?.TODOS_PRODUTOS} />
                ) : (
                    <span className="m-5 text-xl text-violet-900">
                        Ainda não há produtos cadastrados!
                    </span>
                )}
            </motion.main>
        </>
    );
};

export default Home;
