import { useEffect } from 'react';
import Router, { useRouter } from 'next/router';
import { useSelector } from 'react-redux';
import { RootState } from 'app';
import LoadingPage from 'components/common/ui/LoadingPage';
import { useSession } from 'next-auth/react';
import { useDispatch } from 'react-redux';
import { clearCart } from 'app/carrinho.store';
import Head from 'next/head';
import { motion } from 'framer-motion';
import { BsCheckCircleFill } from 'react-icons/bs';
import { BiHome } from 'react-icons/bi';

const Obrigado = () => {
    const { query } = useRouter();
    const {
        data: { user },
    } = useSession();
    const dispatch = useDispatch();

    useEffect(() => {
        if (query.success) {
            dispatch(clearCart(user.id));
        }
    }, [query]);

    return (
        <>
            <Head>
                <title>Coelhão Store</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <motion.main
                exit={{ opacity: 0 }}
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                transition={{ duration: 0.3 }}
                className="flex h-screen w-screen flex-col items-center justify-center bg-violet-800"
            >
                <BsCheckCircleFill className="mb-10 text-[150px] text-white" />
                <h1 className="mb-4 text-4xl text-white">
                    Pedido realizado com sucesso!
                </h1>
                <span className="mb-10 text-violet-300">
                    Muito obrigado por comprar com a Coelhão Store 😉
                </span>
                <button
                    onClick={() => Router.push('/')}
                    className="flex items-center justify-between rounded-3xl bg-white py-4 px-4 text-xl text-violet-600 shadow-lg"
                >
                    <BiHome className="mr-3 text-2xl" />
                    <span className="text-lg">Voltar a página principal</span>
                </button>
            </motion.main>
        </>
    );
};

Obrigado.auth = {
    role: 'user',
    loading: <LoadingPage />,
    unauthorized: '/Login',
};

export default Obrigado;
