import { useSession } from 'next-auth/react';
import { motion } from 'framer-motion';
import LoadingPage from 'components/common/ui/LoadingPage';
import Card from 'components/common/ui/Card';

import { BiAddToQueue, BiEdit } from 'react-icons/bi';
import {
    MdOutlineAddCircleOutline,
    MdRemoveCircleOutline,
} from 'react-icons/md';

import Head from 'next/head';
import ActionButton from 'components/common/ui/ActionButton';
import IcontTitle from 'components/common/ui/IconTitle';
import { FiShoppingBag, FiClock } from 'react-icons/fi';
import { MdManageAccounts } from 'react-icons/md';
import Modal from 'components/common/ui/Modal';
import { useEffect, useState } from 'react';
import { NextPage } from 'next';

interface Props {
    actionData: {
        onClickAdd: JSX.Element;
    };
}

interface AuthProps {
    auth: {
        role: string;
        loading: JSX.Element;
        unauthorized: string;
    };
}

const Home: NextPage<Props> & AuthProps = ({ actionData }) => {
    const [visible, setVisible] = useState(false);

    return (
        <>
            <Head>
                <title>Admin Dashboard</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <motion.div
                exit={{ opacity: 0 }}
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                transition={{ duration: 0.3 }}
                className="flex w-full justify-center bg-violet-100 sm:py-10"
            >
                <Card width="w-10/12 justify-start">
                    <div className="flex w-full flex-col items-center">
                        <span className="my-4 flex items-center text-3xl text-violet-600 sm:mb-0 sm:mt-2">
                            <FiShoppingBag className="mr-3" />
                            <span>Pedidos</span>
                        </span>

                        <div className="my-8 h-0.5 w-4/6 rounded-xl bg-violet-200" />

                        <div>
                            <IcontTitle
                                icon={<MdManageAccounts />}
                                title="Gerenciamento"
                            />

                            <div className="mt-6 flex">
                                <button className="mx-4 sm:mx-8">
                                    <ActionButton
                                        icon={<BiAddToQueue />}
                                        title={'Adicionar'}
                                    />
                                </button>
                                <div className="mx-4 sm:mx-8">
                                    <ActionButton
                                        icon={<BiEdit />}
                                        title={'Alterar'}
                                    />
                                </div>
                                <div className="mx-4 sm:mx-8">
                                    <ActionButton
                                        icon={<MdRemoveCircleOutline />}
                                        title={'Remover'}
                                    />
                                </div>
                            </div>
                        </div>

                        <div className="my-8 h-0.5 w-4/6 rounded-xl bg-violet-200" />

                        <div className="flex w-11/12 flex-col items-center">
                            <IcontTitle
                                icon={<FiClock />}
                                title={'Últimos pedidos'}
                            />
                        </div>
                    </div>
                </Card>
            </motion.div>
        </>
    );
};

Home.auth = {
    role: 'admin',
    loading: <LoadingPage />,
    unauthorized: '/Login',
};

export default Home;
